In [36]:
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [37]:
df=pd.read_csv("predictive_maintenance_dataset.csv")

In [38]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Machine failure          10000 non-null  int64
 9   TWF                      10000 non-null  int64
 10  HDF                      10000 non-null  int64
 11  PWF                      10000 non-null  int64
 12  OSF                      10000 non-null  int64
 13  RNF                      10000 non-null  int64
dtypes: float64(3), int64(9), object(2)
memory usage: 1.1+ MB

In [40]:
df.isnull().sum()

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

In [41]:
df.describe()

,UDI,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,300.004930,310.005560,1538.776100,39.986910,107.951000,0.033900,0.004600,0.011500,0.009500,0.009800,0.00190
std,2886.89568,2.000259,1.483734,179.284096,9.968934,63.654147,0.180981,0.067671,0.106625,0.097009,0.098514,0.04355
min,1.00000,295.300000,305.700000,1168.000000,3.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,298.300000,308.800000,1423.000000,33.200000,53.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,5000.50000,300.100000,310.100000,1503.000000,40.100000,108.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,7500.25000,301.500000,311.100000,1612.000000,46.800000,162.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,10000.00000,304.500000,313.800000,2886.000000,76.600000,253.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000

In [42]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Type"]=le.fit_transform(df["Type"])

In [43]:
df["Product ID"]=le.fit_transform(df["Product ID"])

In [44]:
x = df[[
    "Air temperature [K]",
    "Process temperature [K]",
    "Rotational speed [rpm]",
    "Torque [Nm]",
    "Tool wear [min]"
]]

y = df["Machine failure"]

In [45]:
df

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,7003,2,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,1003,1,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,1004,1,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,1005,1,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,1006,1,298.2,308.7,1408,40.0,9,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,9997,2,298.8,308.4,1604,29.5,14,0,0,0,0,0,0
9996,9997,1001,0,298.9,308.4,1632,31.8,17,0,0,0,0,0,0
9997,9998,9998,2,299.0,308.6,1645,33.4,22,0,0,0,0,0,0
9998,9999,1002,0,299.0,308.7,1408,48.5,25,0,0,0,0,0,0
9999,10000,9999,2,299.0,308.7,1500,40.2,30,0,0,0,0,0,0

In [46]:
x_train,x_test,y_train,y_test=train_test_split( x, y, test_size=0.2, random_state=42)

In [47]:
print(df["Machine failure"].value_counts())

Machine failure
0    9661
1     339
Name: count, dtype: int64

In [48]:
pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in c:\users\hp 250 g9\appdata\local\programs\python\python313\lib\site-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\hp 250 g9\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn) (2.3.4)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\users\hp 250 g9\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\users\hp 250 g9\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn) (1.7.2)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in c:\users\hp 250 g9\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\users\hp 250 g9\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn) (1.5.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\hp 250 g9\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [49]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

# Define features and target
X = df[
    [
        "Air temperature [K]",
        "Process temperature [K]",
        "Rotational speed [rpm]",
        "Torque [Nm]",
        "Tool wear [min]"
    ]
]

y = df["Machine failure"]

# Split first 
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

# Apply SMOTE only on training data
smote = SMOTE(random_state=42)

x_train_balanced, y_train_balanced = smote.fit_resample(x_train, y_train)

print(y_train_balanced.value_counts())

Machine failure
0    7729
1    7729
Name: count, dtype: int64

In [50]:
print(y_train_balanced.value_counts())

Machine failure
0    7729
1    7729
Name: count, dtype: int64

In [51]:
scaler=StandardScaler()
x_train_balanced=scaler.fit_transform(x_train_balanced)
x_test=scaler.transform(x_test)

In [52]:
lr=LogisticRegression()
lr.fit(x_train_balanced,y_train_balanced)

LogisticRegression()

In [53]:
y_pred_lr=lr.predict(x_test)

In [54]:
y_pred_lr

array([1, 0, 0, ..., 1, 1, 0], shape=(2000,))

In [55]:
y_test

2997    0
4871    0
3858    0
951     0
6463    0
       ..
1686    0
6952    0
9954    0
5728    0
9191    0
Name: Machine failure, Length: 2000, dtype: int64

In [56]:
accuracy_score(y_test,y_pred_lr)

0.5155

In [57]:
dt=DecisionTreeClassifier()
dt.fit(x_train_balanced,y_train_balanced)

DecisionTreeClassifier()

In [58]:
y_pred_dt=dt.predict(x_test)

In [59]:
y_pred_dt

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [60]:
accuracy_score(y_test,y_pred_dt)

0.85

In [61]:
print("classification_report:\n",classification_report(y_test,y_pred_dt))

classification_report:
               precision    recall  f1-score   support

           0       0.97      0.88      0.92      1932
           1       0.03      0.10      0.04        68

    accuracy                           0.85      2000
   macro avg       0.50      0.49      0.48      2000
weighted avg       0.93      0.85      0.89      2000

In [62]:
rf=RandomForestClassifier()
rf.fit(x_train_balanced,y_train_balanced)

RandomForestClassifier()

In [63]:
y_pred_rf=rf.predict(x_test)

In [64]:
y_pred_rf

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [65]:
accuracy_score(y_test,y_pred_rf)

0.9075

In [66]:
from sklearn.metrics import roc_auc_score

# For Random Forest
y_prob = rf.predict_proba(x_test)[:,1]
roc_score = roc_auc_score(y_test, y_prob)

print("ROC-AUC Score:", roc_score)

ROC-AUC Score: 0.48985735598587266

In [67]:
print(rf.classes_)

[0 1]

In [68]:
print(y_test.value_counts())

Machine failure
0    1932
1      68
Name: count, dtype: int64

In [69]:
print("Number of columns:", len(x.columns))
print("Number of importances:", len(rf.feature_importances_))

Number of columns: 5
Number of importances: 5

In [70]:
importance = pd.DataFrame({
    "Feature": x.columns,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

print("\nFeature Importance:\n")
print(importance)

Feature Importance:

                   Feature  Importance
2   Rotational speed [rpm]    0.223228
4          Tool wear [min]    0.200022
1  Process temperature [K]    0.197069
0      Air temperature [K]    0.196166
3              Torque [Nm]    0.183516

In [71]:

import joblib
joblib.dump(rf, "machine_failure_model.pkl")

print("\nModel saved successfully!")

Model saved successfully!

In [72]:
print(X_train.shape)

(8000, 5)

In [73]:
print(rf.n_features_in_)

5